# Generated by Django 4.1.4 on 2022-12-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=512)),
                ('idade', models.CharField(help_text='Idade', max_length=512)),
                ('profissao', models.CharField(help_text='Profissão', max_length=512)),
                ('jogo_preferido', models.CharField(help_text='Seu jogo preferido', max_length=512)),
                ('id_usuario', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'sql_query',
            },
        ),
    ]
